spring:
  application:
    name: liquibase
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-main.yaml
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    user: sa
    password:
    show-summary: verbose